[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "development"
  NETLIFY_USE_CACHE = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"


[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/**.svg"
    [headers.values]
      Content-Type = "image/svg+xml"

[[headers]]
  for = "/**.png"
    [headers.values]
      Content-Type = "image/png"

[[headers]]
  for = "/**.jpg"
    [headers.values]
      Content-Type = "image/jpeg"
