[build]
  command = "rm -rf .parcel-cache dist && npm run build"
  publish = "dist"

[build.environment]
NODE_ENV = "production"
NETLIFY_USE_CACHE = "false"

[[redirects]]
from = "/api/courses"
to = "https://webbutveckling.miun.se/files/ramschema_ht24.json"
status = 200
force = true
headers = { Access-Control-Allow-Origin = "*" }
