[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
NODE_ENV = "production"
NETLIFY_USE_CACHE = "false"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
